### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by ghork125** [ch3p4ll3/QBittorrentBot#13]
Hi, when i run python3 main.py, i see this error:
qbittorrent@qbittorrent:/opt/qbittorrent-bot$ python3 main.py      
Traceback (most recent call last):
  File "/opt/qbittorrent-bot/main.py", line 1, in <module>
    from src.bot import app, scheduler
ModuleNotFoundError: No module named 'src'

What can i do? 
OS: Ubuntu 22.04

Thanks in advance.

**Comment by ch3p4ll3** [comment]
What version of python are you using?

**Comment by ghork125** [comment]
Python 3.10.6

**Comment by ch3p4ll3** [comment]
Ok, what is the output of `ls /opt/qbittorrent-bot`

**Comment by ghork125** [comment]
qbittorrent@qbittorrent:~$ ls /opt/qbittorrent-bot/
Dockerfile  __pycache__  config.py          main.py                 utils.py
LICENSE     bot.py       custom_filters.py  qbittorrent_control.py
README.md   config.json  db_management.py   requirements.txt

**Comment by ch3p4ll3** [comment]
Have you moved all the files inside the src folder in /opt/qbittorrent-bot/ ? I suggest you to re-download the repo and follow [these](https://github.com/ch3p4ll3/QBittorrentBot#running-without-docker) steps

**Comment by ch3p4ll3** [comment]
How did you download the repo? From what I have seen it appears that you moved the files out of the src folder, then you deleted the folder. This is what I saw from the output of the ls command.

**Comment by ghork125** [comment]
I tried again, deleted everything that was, went from under the root.

```
mkdir /opt
cd /opt/
git clone https://github.com/ch3p4ll3/QBittorrentBot.git
cd QBittorrentBot/
cp /tmp/config.json /opt/QBittorrentBot/config.json
```
checked what is in my folder:

```
root@qbittorrent:/opt/QBittorrentBot# ls
Dockerfile  README.md    config.json.template  requirements.txt
LICENSE     config.json  main.py               src
```
and continued

```
root@qbittorrent:/opt/QBittorrentBot# pip3 install -r requirements.txt
Requirement already satisfied: APScheduler==3.9.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (3.9.1)
Requirement already satisfied: async-lru==1.0.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (1.0.3)
Requirement already satisfied: certifi==2022.9.24 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (2022.9.24)
Requirement already satisfied: charset-normalizer==2.1.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (2.1.1)
Requirement already satisfied: idna==3.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 5)) (3.4)
Requirement already satisfied: pony==0.7.16 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (0.7.16)
Requirement already satisfied: psutil==5.9.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (5.9.2)
Requirement already satisfied: pyaes==1.6.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 8)) (1.6.1)
Requirement already satisfied: pydantic==1.10.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 9)) (1.10.2)
Requirement already satisfied: Pyrogram==2.0.57 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 10)) (2.0.57)
Requirement already satisfied: PySocks==1.7.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 11)) (1.7.1)
Requirement already satisfied: pytz==2022.2.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 12)) (2022.2.1)
Requirement already satisfied: pytz-deprecation-shim==0.1.0.post0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 13)) (0.1.0.post0)
Requirement already satisfied: qbittorrent-api==2022.8.38 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 14)) (2022.8.38)
Requirement already satisfied: requests==2.28.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 15)) (2.28.1)
Requirement already satisfied: six==1.16.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 16)) (1.16.0)
Requirement already satisfied: TgCrypto==1.2.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 17)) (1.2.3)
Requirement already satisfied: typing_extensions==4.3.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 18)) (4.3.0)
Requirement already satisfied: tzdata==2022.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 19)) (2022.2)
Requirement already satisfied: tzlocal==4.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 20)) (4.2)
Requirement already satisfied: urllib3==1.26.12 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 21)) (1.26.12)
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3/dist-packages (from APScheduler==3.9.1->-r requirements.txt (line 1)) (59.6.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

rewritten the path to the file:

```
nano /opt/QBittorrentBot/src/config.py
with open('/opt/QBittorrentBot/config.json', 'r') as config_json:
```

tried to run:

```
root@qbittorrent:/opt/QBittorrentBot# python3 main.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pony/orm/dbapiprovider.py", line 55, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pony/orm/dbapiprovider.py", line 231, in connect
    return provider.pool.connect()
  File "/usr/local/lib/python3.10/dist-packages/pony/orm/dbapiprovider.py", line 352, in connect
    pool._connect()
  File "/usr/local/lib/python3.10/dist-packages/pony/orm/dbproviders/sqlite.py", line 667, in _connect
    pool.con = con = sqlite.connect(filename, isolation_level=None, **pool.kwargs)
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/QBittorrentBot/main.py", line 1, in <module>
    from src.bot import app, scheduler
  File "/opt/QBittorrentBot/src/bot.py", line 13, in <module>
    from src.utils import torrent_finished, convert_size, convert_eta
  File "/opt/QBittorrentBot/src/utils.py", line 5, in <module>
    from src import db_management
  File "/opt/QBittorrentBot/src/db_management.py", line 6, in <module>
    db.bind(provider='sqlite', filename='/app/config/database.sqlite', create_db=True)
  File "/usr/local/lib/python3.10/dist-packages/pony/orm/core.py", line 765, in bind
    self._bind(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pony/orm/core.py", line 787, in _bind
    self.provider = provider_cls(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pony/orm/dbproviders/sqlite.py", line 345, in __init__
    DBAPIProvider.__init__(provider, database, is_shared_memory_db, filename, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pony/orm/dbapiprovider.py", line 131, in __init__
    connection, is_new_connection = provider.connect()
  File "<string>", line 2, in connect
  File "/usr/local/lib/python3.10/dist-packages/pony/orm/dbapiprovider.py", line 72, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: unable to open database file
```
maybe something is going wrong with me at the moment `pip3 install -r requirements.txt`?

**Comment by ghork125** [comment]
just wrote and saw that

```
  File "/opt/QBittorrentBot/src/db_management.py", line 6, in <module>
    db.bind(provider='sqlite', filename='/app/config/database.sqlite', create_db=True)
```
`/app/config/` this is the way when using docker, without docker there is no such thing on my system

**Comment by ch3p4ll3** [comment]
Yep without docker you have to change that path with something else. Like ./database.sqlite

**Comment by ghork125** [comment]
it works!

**Comment by ghork125** [comment]
Thanks a lot
