### ISSUE TITLE
pony.orm.core.ObjectNotFound

### ISSUE THREAD

**Issue by AlivE-git** [ch3p4ll3/QBittorrentBot#20]
Pull container from dockerhub. The logs show an error:
```
Support[MY_USER_ID]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/src/bot.py", line 375, in on_text
    action = db_management.read_support(message.from_user.id)
  File "/app/src/db_management.py", line 23, in read_support
    return Support[chat_id].Action
  File "/usr/local/lib/python3.10/site-packages/pony/orm/core.py", line 3991, in __getitem__
    return entity._find_one_(kwargs)
  File "/usr/local/lib/python3.10/site-packages/pony/orm/core.py", line 4115, in _find_one_
    if obj is None: throw(ObjectNotFound, entity, pkval)
  File "/usr/local/lib/python3.10/site-packages/pony/utils/utils.py", line 99, in throw
    raise exc
pony.orm.core.ObjectNotFound: Support[MY_USER_ID]
```

**Comment by ch3p4ll3** [comment]
Hi, I tried to correct the error, try update the image when CI is done

**Comment by AlivE-git** [comment]
Now this 😅 :
```
Attribute Support.Action is required
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/src/bot.py", line 375, in on_text
    action = db_management.read_support(message.from_user.id)
  File "/app/src/db_management.py", line 26, in read_support
    created = Support(Action="", id=chat_id)
  File "/usr/local/lib/python3.10/site-packages/pony/orm/core.py", line 4706, in __init__
    avdict[attr] = attr.validate(val, obj, from_db=False)
  File "/usr/local/lib/python3.10/site-packages/pony/orm/core.py", line 2537, in validate
    throw(ValueError, 'Attribute %s is required' % (
  File "/usr/local/lib/python3.10/site-packages/pony/utils/utils.py", line 99, in throw
    raise exc
ValueError: Attribute Support.Action is required
```

**Comment by ch3p4ll3** [comment]
Woopsy, now fixed

**Comment by ch3p4ll3** [comment]
Sorry for the wait, I checked a little bit and it sends you that exception because there is no /help command. By sending that command he interprets it as if it was an action to be performed(eg: add a magnet/torrent etc). If you try to start the bot with /start and add a magnet you will see that it will work.

**Comment by AlivE-git** [comment]
Оh, now it works. Thanks a lot)
I thought that when sending an unknown command, bot should respond with some kind of message.

**Comment by ch3p4ll3** [comment]
No problem. When I have some spare time I'm starting to rewrite some of the code, including a message if you send an unknown command or message
