### ISSUE TITLE
Add Torrent (Error)

### ISSUE THREAD

**Issue by krutophistalex** [ch3p4ll3/QBittorrentBot#48]
2024-02-06 16:48:11,420 - pyrogram.dispatcher - ERROR - inject_user.<locals>.wrapper() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/home/krutofa/.local/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/krutofa/scripts/QBittorrentBot/src/utils.py", line 79, in wrapper
    await func(client, message, user)
  File "/home/krutofa/scripts/QBittorrentBot/src/bot/plugins/callbacks/category/category_callbacks.py", line 120, in category
    await add_torrent_callback(client, callback_query, user)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by krutophistalex** [comment]
![image](https://github.com/ch3p4ll3/QBittorrentBot/assets/15141096/3005d751-1122-48d4-99f5-a021098d436e)

**Comment by ch3p4ll3** [comment]
Hi, how are u running the bot? Docker? Try getting the latest update

**Comment by krutophistalex** [comment]
Running without docker
Clone this repo git clone https://github.com/ch3p4ll3/QBittorrentBot.git
Move in the project directory
Install dependencies with pip3 install -r requirements.txt
Create a config.json file
Start the bot with python3 main.py

**Comment by krutophistalex** [comment]
Git clone today

**Comment by ch3p4ll3** [comment]
@krutophistalex Could you pull the latest commit?

**Comment by krutophistalex** [comment]
I'll do this when I'm near the computer, I'll post it, thanks
